#!/bin/env bash
  
wid="$1"
#class="$2"
#instance="$3"
#eval "$4"
#title="$(xtitle "$wid")"
title="$(xprop -id "$wid" WM_NAME | sed -nE 's,^WM_NAME[(]STRING[)] = "(.*)"$,\1,p')"

[[ -z "$state" && "$title" = 'floatme' ]] \
    && echo 'state=floating'

