- name: Install Sway and Sway-related packages
  ansible.builtin.package:
    name:
      - sway
      - swayidle
    state: present
    update_cache: true
  become: true
- name: Install Swaylock Effects & Swayr
  ansible.builtin.include_role:
    name: util-yay
  vars:
    yay_packages:
      - swaylock-effects-git
      - swayr
      - libinput-gestures
- name: Symlink Sway-related dotfiles
  ansible.builtin.include_role:
    name: util-dotfiles
- name: Enable startup services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    scope: user
  with_items:
    - swayidle
    - swayrd
    - libinput-gestures
# required by libinput-gestures
- name: Add user '{{ lookup('env', 'USER') }}' to input group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - input
    append: true
  become: true
