- name: Install Hyprland
  ansible.builtin.include_role:
    name: util-yay
  vars:
    yay_packages:
      - hyprland-bin
- name: Symlink Sway-related dotfiles
  ansible.builtin.include_role:
    name: util-dotfiles
