#! /bin/sh

setxkbmap -option grp:win_space_toggle us,ru &
pgrep -x sxhkd > /dev/null || sxhkd &
greenclip daemon &
xsetroot -cursor_name left_ptr &
picom --backend glx &
feh --bg-fill ~/Pictures/walls/Paul\ Chadeisson/YbK0r0b.jpg &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a '*:*:floatme' state=floating
bspc rule -a Zathura state=tiled

bspc config external_rules_command ~/.config/bspwm/external_rules
