---
- name: Set up defiant
  hosts: localhost
  roles:
    - base-git
    - base-ssh-client
    - base-zsh
    - update-script
    - yubikey
    - stack-containers
    - application-helix
  tasks:
    - name: Set timezone to America/New_York
      community.general.timezone:
        name: America/New_York
