#! /usr/bin/env bash
# Script adapted from https://github.com/MatteoJoliveau/nix-dotfiles/blob/master/nixos/install.sh

set -Eeo pipefail

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LOCAL_NIXOS_DIR="$here/nixos"
NIXOS_DIR="/etc/nixos"
MACHINE="$(hostname)"

usage() {
    echo "Usage: install.sh [flags] <machine-name>"
    echo
    echo "Symlinks the NixOS configuration for the current machine (defaults to the machine hostname `hostname`)"
    echo
    echo "  --dry-run   print the commands without executing them"
    echo "  -h, --help  print this message and exit"
    exit 1
}

main() {
    if [ "$EUID" -ne 0 ]; then
        echo "Please run this script as root"
        exit 1
    fi

    if [ ! -z "$DRY_RUN_CMD" ]; then
        echo "DRY RUN"
        echo ""
    fi

    MACHINE_DIR="$LOCAL_NIXOS_DIR/machines/$MACHINE"
    if [ ! -d "$MACHINE_DIR" ]; then
      echo "No host defined for \"$MACHINE_DIR\""
      echo "Available hosts:"
      ls -d $LOCAL_NIXOS_DIR/machines/*/ | xargs -I '{}' basename '{}'
      exit 1
    fi

    echo "Installing NixOS configuration:"

    echo "Adding nixos-hardware channel..."
    $DRY_RUN_CMD nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
    $DRY_RUN_CMD  nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager
    $DRY_RUN_CMD nix-channel --update

    echo "Removing $NIXOS_DIR for clean symlink..."
    $DRY_RUN_CMD rm -rf "$NIXOS_DIR"

    echo "Linking $LOCAL_NIXOS_DIR to $NIXOS_DIR..."
    $DRY_RUN_CMD ln -s "$LOCAL_NIXOS_DIR" "$NIXOS_DIR"

    echo "Creating local-machine.nix..."
    echo -e "# This file was generated by link_config.sh\n\"$MACHINE\"" \
      > "$LOCAL_NIXOS_DIR/local-machine.nix"

    echo "Done"
    echo
    echo "Now you can run nixos-rebuild switch to activate the system configuration"
}

for arg in "$@"; do
  shift
  case "$arg" in
    "-h"|"--help") usage ;;
    "--dry-run") DRY_RUN_CMD="echo $" ;;
    *) MACHINE="$arg"
  esac
done

main
