---
- name: Set up casper-magi
  hosts: localhost
  roles:
    - docker
    - ssh-client
    - git
    - sway
    # - hyprland
    - zsh
    - pywal
    - yubikey
    - update-script
    - stack-security
  tasks:
    - name: Symlink files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/yukon/{{ item }}"
        path: "~/{{ item }}"
        state: link
      with_items:
        - .config/sway/config.d/yukon
    - name: Set timezone to America/New_York
      community.general.timezone:
        name: America/New_York
