---
- name: Set up yukon
  hosts: localhost
  roles:
  - zsh
  - docker
  - sway
  tasks:
    - name: Install packages specific to GPD Pocket 2
      ansible.builtin.package:
        name:
          # thermal / battery management
          - thermald
          - tlp
        state: present
        update_cache: yes
      become: yes
    - name: Start services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - thermald
        - tlp
      become: true
    - name: Symlink files
      file:
        src: "{{ playbook_dir }}/files/yukon/{{ item }}"
        path: "~/{{ item }}"
        state: link
      with_items:
        - .config/sway/config.d/yukon
