---
- name: Set up casper-magi
  hosts: localhost
  roles:
    - docker
    - ssh-client
    - git
    - sway
    # - hyprland
    - zsh
    - yubikey
    - update-script
  tasks:
    - name: Symlink files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/yukon/{{ item }}"
        path: "~/{{ item }}"
        state: link
      with_items:
        - .config/sway/config.d/yukon
