---
- name: Set up casper-magi
  hosts: localhost
  roles:
    - base-git
    - base-ssh-client
    - base-zsh
    - update-script
    - yubikey
    - application-kitty
    - stack-containers
    - stack-security
    - desktop-sway
    - desktop-hyprland
    - pywal
  tasks:
    - name: Symlink files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/yukon/{{ item }}"
        path: "~/{{ item }}"
        state: link
      with_items:
        - .config/sway/config.d/yukon
    - name: Set timezone to America/New_York
      community.general.timezone:
        name: America/New_York
