- name: Install Gnome Keyring
  ansible.builtin.package:
    name: gnome-keyring
    state: present
    update_cache: true
  become: true
- name: Add auth pam_gnome_keyring rule to login PAM after auth system-local-login
  community.general.pamd:
    name: login
    type: auth
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    state: after
  become: true
- name: Add session pam_gnome_keyring to login PAM after password system-local-login
  community.general.pamd:
    name: login
    type: password
    control: include
    module_path: system-local-login
    new_type: session
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    module_arguments: auto_start
    state: after
  become: true
