- name: Install Gnome Keyring
  ansible.builtin.package:
    name: gnome-keyring
    state: present
    update_cache: true
  become: true
- name: Copy PAM configuration for Gnome Keyring
  ansible.builtin.copy:
    src: /etc/pam.d/login
    dest: /etc/pam.d/login
  become: true
