- name: Install Gnome Keyring
  ansible.builtin.package:
    name: gnome-keyring
    state: present
    update_cache: yes
  become: yes
- name: Copy PAM configuration for Gnome Keyring
  copy:
    src: /etc/pam.d/login
    dest: /etc/pam.d/login
  become: yes
