- name: Install security-related software
  ansible.builtin.package:
    name:
      - nmap
      - wireshark-qt
      - macchanger
    state: present
    update_cache: true
  become: true
- name: Add Wireshark group to user {{ lookup('env', 'USER') }}
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - wireshark
    append: true
  become: true
