- name: Install BSPWM and its dependencies
  ansible.builtin.package:
    name:
      - bspwm
      - sxhkd
    state: present
    update_cache: yes
  become: true
- name: Symlink bspwm-related dotfiles
  include_role:
    name: dotfiles