- name: Set up Docker repo (Fedora)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 644
  become: true
  when: ansible_distribution == "Fedora"
- name: Install Docker and K8s related packages
  ansible.builtin.package:
    name: "{{ packages[ansible_distribution] }}"
    state: present
    update_cache: true
  become: true
- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
- name: Add Docker group to user {{ lookup('env', 'USER') }}
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
    append: true
  become: true
