- name: Install Docker (Docker)
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
      - kubectl
      - helm
    state: present
    update_cache: true
  become: true
- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
- name: Add user '{{ lookup('env', 'USER') }}' to Docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
    append: true
  become: true
