- name: Install zsh and zsh plugins
  ansible.builtin.package:
    name:
      - zsh
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    state: present
    update_cache: yes
  become: yes
- name: Symlink zsh dotfiles
  include_role:
    name: dotfiles
- name: change user shell to zsh 
  vars:
    the_user: "{{ ansible_user_id }}"
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
