- name: Install zsh and zsh plugins
  ansible.builtin.package:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present
    update_cache: true
  become: true
- name: Symlink zsh dotfiles
  ansible.builtin.include_role:
    name: dotfiles
- name: change user shell to zsh
  vars:
    the_user: "{{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
