- name: Install zsh
  package:
    name: zsh
    state: present
    update_cache: yes
  become: yes
- name: Create required directories for zsh
  file:
    path: ~/{{ item }}
    state: directory
  with_items:
    - ".config/zshrc.d"
    # local executables live here
    - ".local/bin"
- name: Symlink zsh dotfiles
  include_role:
    name: dotfiles
- name: change user shell to zsh 
  vars:
    the_user: "{{ ansible_user_id }}"
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes