- name: Install Git
  ansible.builtin.package:
    name:
      - openssh
    state: present
  become: true
- name: Assert directory permissions
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
- name: Symlink ssh-client dependencies
  ansible.builtin.include_role:
    name: nikitawootten.dotfiles
- name: Assert config permissions
  ansible.builtin.file:
    path: ~/.ssh/config.d
    state: directory
    mode: "0700"
