- name: Install Git
  ansible.builtin.package:
    name:
      - git
    state: present
  become: yes
- name: Configure Git
  ansible.builtin.shell: |
    git config --global user.name "Nikita Wootten"
    git config --global user.email nikita.wootten@gmail.com
    git config --global core.editor vim
    git config --global fetch.prune true
    git config --global pull.rebase false


