- name: Install Git
  ansible.builtin.package:
    name:
      - git
    state: present
  become: true
- name: Get the state of ~/.gitconfig before updates
  ansible.builtin.stat:
    path: ~/.gitconfig
  register: before
- name: Configure Git
  ansible.builtin.shell: |
    git config --global user.name "Nikita Wootten"
    git config --global user.email nikita.wootten@gmail.com
    git config --global core.editor vim
    git config --global fetch.prune true
    git config --global pull.rebase false
  changed_when: false
- name: Get the state of ~/.gitconfig after updates
  ansible.builtin.stat:
    path: ~/.gitconfig
  register: after
  changed_when: before.stat.exists == false or before.stat.checksum != after.stat.checksum
