- name: Install Yubikey and PGP-related packages
  ansible.builtin.package:
    name:
      - gnupg
      - pcsclite
      - ccid
      #- hopenpgp-tools
      - yubikey-personalization
      - yubikey-manager
      - yubikey-touch-detector
    state: present
    update_cache: yes
  become: yes
- name: Enable pcscd
  ansible.builtin.systemd:
    name: pcscd
    enabled: yes
    state: started
  become: yes
- name: Symlink configs
  include_role:
    name: dotfiles
- name: Enable yubikey-touch-detector
  ansible.builtin.systemd:
    name: yubikey-touch-detector
    enabled: yes
    state: started
    scope: user
- name: List the keys before importing
  ansible.builtin.command: gpg -K
  changed_when: false
  register: gpg_before
- name: Import GPG key
  ansible.builtin.command: gpg --batch --recv {{ key_id }}
  changed_when: false
- name: Trust GPG key
  ansible.builtin.shell: echo -e "5\ny\n" | gpg --command-fd 0 --edit-key {{ key_id }} trust
  changed_when: false
- name: List the keys after importing
  ansible.builtin.command: gpg -K
  register: gpg_after
  changed_when: gpg_before.stdout != gpg_after.stdout
- name: Get the state of ~/.gitconfig before updates
  ansible.builtin.stat:
    path: ~/.gitconfig
  register: gitconfig_before
- name: Configure Git for keysigning
  ansible.builtin.shell: |
    git config --global commit.gpgsign true
    git config --global user.signingkey {{ key_id }}
  changed_when: false
- name: Get the state of ~/.gitconfig after updates
  ansible.builtin.stat:
    path: ~/.gitconfig
  register: gitconfig_after
  changed_when: gitconfig_before.stat.exists == false or gitconfig_before.stat.checksum != gitconfig_after.stat.checksum
