- name: Install zsh and zsh plugins
  ansible.builtin.package:
    name: "{{ packages[ansible_distribution] }}"
    state: present
    update_cache: true
  become: true
- name: Symlink zsh dotfiles
  ansible.builtin.include_role:
    name: nikitawootten.dotfiles
- name: Change user shell to zsh
  vars:
    the_user: "{{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
