- name: Install base x tools
  ansible.builtin.package:
    name:
      - xorg-xinit
      - xorg-xinput
      - xorg-setxkbmap
      - xclip
      # secrets and ssh agent management
      - gnome-keyring
      # fonts
      - ttf-jetbrains-mono
      - noto-fonts
      - noto-fonts-extra
      - noto-fonts-cjk
      - noto-fonts-emoji
      # eye candy
      - picom
      - python-pywal
      - feh
    state: present
    update_cache: yes
  become: yes
- name: Symlink base wm dotfiles
  include_role:
    name: dotfiles
  vars:
    dotfiles_src: files/user
- name: Copy PAM configuration for Gnome Keyring
  copy:
    src: system/etc/pam.d/login
    dest: /etc/pam.d/login
  become: yes