- name: Install Docker package dependencies (Ubuntu/Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  become: true
- name: Add Docker GPG key (Ubuntu/Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ (ansible_distribution == 'Ubuntu') | ternary('ubuntu', 'debian') }}/gpg
    state: present
  become: true
- name: Add Docker repository (Ubuntu/Debian)
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/{{ (ansible_distribution == 'Ubuntu') | ternary('ubuntu', 'debian') }} {{ ansible_distribution_release }} stable
    state: present
  become: true
- name: Install Docker (Ubuntu/Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  become: true
