- import_tasks: install_arch.yaml
  when: ansible_distribution == "Arch Linux" or
        ansible_distribution == "Archlinux"
- import_tasks: install_debian.yaml
  when: ansible_distribution == "Debian" or
        ansible_distribution == "Ubuntu"
- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
- name: Add user '{{ lookup('env', 'USER') }}' to Docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
    append: true
  become: true
