- name: Install Sway and Sway-related packages
  ansible.builtin.package:
    name:
      - sway
      - swaylock
      - swayidle
      # wayland utils
      - wl-clipboard
      # dmenu replacement
      - wofi
      # backwards compatibility with x
      - xorg-xwayland
      # screen capture/shot utilities
      - grim
      - slurp
      - wf-recorder
    state: present
    update_cache: yes
  become: yes
- name: Symlink Sway-related dotfiles
  include_role:
    name: dotfiles
- name: Enable startup services
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  with_items:
    - gnome-keyring-daemon
    - swayidle
