- name: Install Sway and Sway-related packages
  ansible.builtin.package:
    name:
      - sway
      # - swaylock
      - swayidle
      # wayland utils
      - wl-clipboard
      - brightnessctl
      - mako
      # dmenu replacement
      - wofi
      # backwards compatibility with x
      - xorg-xwayland
      - xorg-xhost
      # screen capture/shot utilities
      - grim
      - slurp
      - wf-recorder
      - xdg-desktop-portal-wlr
      # media
      - playerctl
    state: present
    update_cache: true
  become: true
- name: Install Swaylock Effects & Swayr
  ansible.builtin.include_role:
    name: util-yay
  vars:
    yay_packages:
      - swaylock-effects-git
      - swayr
      - libinput-gestures
- name: Symlink Sway-related dotfiles
  ansible.builtin.include_role:
    name: util-dotfiles
- name: Enable startup services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    scope: user
  with_items:
    - swayidle
    - swayrd
    - libinput-gestures
# required by libinput-gestures
- name: Add user '{{ lookup('env', 'USER') }}' to input group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - input
    append: true
  become: true
