- name: Install Sway and Sway-related packages
  ansible.builtin.package:
    name:
      - sway
      - swaylock
      - swayidle
      # wayland utils
      - wl-clipboard
      - brightnessctl
      - mako
      # dmenu replacement
      - wofi
      # backwards compatibility with x
      - xorg-xwayland
      - xorg-xhost
      # screen capture/shot utilities
      - grim
      - slurp
      - wf-recorder
      - xdg-desktop-portal-wlr
    state: present
    update_cache: true
  become: true
- name: Symlink Sway-related dotfiles
  ansible.builtin.include_role:
    name: dotfiles
- name: Enable startup services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    scope: user
  with_items:
    - gnome-keyring-daemon
    - swayidle
