- name: Install Alacritty
  ansible.builtin.package:
    name: alacritty
    state: present
    update_cache: true
  become: true
- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
# did I mention I hate xdg-open?
- name: Symlink Alacritty to ~/.local/bin/xterm
  ansible.builtin.file:
    src: /bin/alacritty
    path: ~/.local/bin/xterm
    state: link
