- name: Create required directories
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
- name: Get playbook info
  ansible.builtin.set_fact:
    playbookBaseName: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('', ' ')).split() | select('match', '^.*[.]ya?ml$') | list | first | basename }}"
- name: Create update script
  ansible.builtin.template:
    src: dotfiles-update.j2
    dest: ~/.local/bin/dotfiles-update
    mode: 0744
